<?php  if ($block->isEnabled()):  ?>
   <div class="actions-toolbar facebook-login">
       <div class="primary">
            <button id="btn_facebook_login" type="submit" class="action save primary" title="<?php echo __('FB Login/Register'); ?>"><span class="fb-logo"></span><span><?php echo __('Facebook Login') ?></span></button>
        </div>
   </div>

   <script>
       require(['excellence/facebooklogin'], function (FacebookPopup) {
           $('btn_facebook_login').observe('click', function () {
               var fbPopup = new FacebookPopup();
               fbPopup.openPopup('<?php echo $block->getLoginUrl()?>', '<?php echo __('Login By Facebook')?>');
           })
       });
   </script>
<?php endif; ?>