<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

?>
<form class="form password forget"
      action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/flogin',array('page'=>$block->getPage())) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
        <div class="field note"><?php /* @escapeNotVerified */ echo __('Email is already registered on our website. Please enter your password to link your account.'); ?></div>
        <div class="field email required">
            <label for="password" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
            <div class="control">
                <input type="hidden" name="email" value="<?php echo $block->getEmail();?>" />
                <input type="password" name="password" alt="password" id="password" class="input-text"  data-validate="{required:true}">
            </div>
        </div>
       
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?php /* @escapeNotVerified */ echo __('Submit') ?></span></button>
        </div>
        
    </div>
</form>